services:
  example-frontend:
    build:
      context: example-frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  example-backend:
    build:
      context: example-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
